### ISSUE TITLE
Futures account API

### ISSUE THREAD

**Issue by yovanoc** [wisespace-io/binance-rs#100]
Hello, great lib, but when are you planning to add account apis for futures? to place order, etc all methods needed for real futures trading

Thanks

**Comment by wisespace-io** [comment]
@yovanoc Futures API is in very early days. But, we got some contributions recently from @chipshort and @vikulikov. Please check the latest version. Contributions are always welcome :)

**Comment by wisespace-io** [comment]
@yovanoc Please check the latest changes in the Futures API
