### ISSUE TITLE
spot depth events don't work.

### ISSUE THREAD

**Issue by KalitaAlexey** [wisespace-io/binance-rs#109]
106d53f810e2d21bd9801cf373b5c8fd821292af (my commit) broke spot `DepthOrderBookEvent` because it doesn't have `pu`, instead they rely on `U` and `u`.

**Comment by dorak88783** [comment]
I didn't review the last commit, but does this means there's not enough test coverage on these events?

**Comment by KalitaAlexey** [comment]
Given `cargo test` succeeds, I guess you don't have tests that ensure that `DepthOrderBookEvent` can be deserialized from json.
