### ISSUE TITLE
Data type mismatch between KlineSummary and Kline

### ISSUE THREAD

**Issue by siegfried** [wisespace-io/binance-rs#136]
[OHLC data in KlineSummary](https://github.com/wisespace-io/binance-rs/blob/29c79997398364e77d20832dda2ed8af098c1194/src/model.rs#L865) is convert to `f64` while OHLC data in Kline remains in string. How about keep them all in string so they can be stored as arbitrary precision number in database?

**Comment by siegfried** [comment]
And is there a need to serialize/deserialize KlineSummary model? It seems a little unnecessary since the API of Kline returns data in nested arrays, right? How about implement a `From` trait for KlineSummary?

**Comment by wisespace-io** [comment]
@siegfried Don't recall why there is this mismatch. Is Binance returning float for the Kline Summary? We could make them string indeed.

**Comment by siegfried** [comment]
Binance returns string for Kline summary. https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data

**Comment by siegfried** [comment]
Please have a look at the the PR. Thanks. @wisespace-io
