### ISSUE TITLE
keep getting "Unauthorized" when call "get_account"

### ISSUE THREAD

**Issue by thetrung** [wisespace-io/binance-rs#144]
I tried sample code on README :

```
use binance::api::*;
use binance::account::*;

fn main() {
    let api_key = Some("YOUR_API_KEY".into());
    let secret_key = Some("YOUR_SECRET_KEY".into());

    let account: Account = Binance::new(api_key, secret_key);

    match account.get_account() {
        Ok(answer) => println!("{:?}", answer.balances),
        Err(e) => println!("Error: {:?}", e),
    }
```

and result didn't change : 

        Error(Msg("Unauthorized"), State { next_error: None, backtrace: InternalBacktrace })
        Error(Msg("Unauthorized"), State { next_error: None, backtrace: InternalBacktrace })

I already enabled Spot Trading + Reading in API management but nothing change.

**Comment by Antifrajz** [comment]
Hello
How did you resolved this issue? @thetrung
