### ISSUE TITLE
Build failed with tungstenite and ring

### ISSUE THREAD

**Issue by LucasSimpson** [wisespace-io/binance-rs#28]
Excuse if this is a naive question, as I'm new to Rust - 

With the version bumps, I'm unable to build. Specifically, I get the following errors:
1) ring 0.16.7: error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
2) tungstenite 0.9.1: error[E0505]: cannot move out of `request` because it is borrowed

**Comment by wisespace-io** [comment]
Interesting, the build is passing as you can see the Badge in the repository. I tried locally a clean build to confirm. Which Rust version are you using? Which OS? linux?

I have  rustc 1.37.0 (eae3437df 2019-08-13)

Could you try the step below?  Please, let me know the outcome

    cargo clean
    cargo update
    cargo build --release

**Comment by LucasSimpson** [comment]
I'm on:

`rustc 1.35.0 (3c235d560 2019-05-20)`

cargo build --release still gives the following:
```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.7/src/lib.rs:69:1
   |
69 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ring`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

However, when I upgraded Rust to `rustc 1.37.0 (eae3437df 2019-08-13)` then the build passes.

**Comment by drbh** [comment]
👍This was helpful - maybe it should be included in the docs?

**Comment by wisespace-io** [comment]
@drbh I added a note to the README
