### ISSUE TITLE
Support for /api/v3/order/test endpoint

### ISSUE THREAD

**Issue by unterkontrolle** [wisespace-io/binance-rs#31]
Hi!

Are you interested in supporting the [Test new order](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade) endpoint?

From an interface point of view, two options come to my mind:
1. Adding a test version for each existing function related to new orders. Example: now we have `Account::limit_buy`, `Account::limit_sell`, etc. and we could add `Account::test_limit_buy`, `Account::test_limit_sell`, etc.
2. Adding a boolean parameter to the existing functions to indicate whether to use the test endpoint or not.

I could help with a pull request.

**Comment by wisespace-io** [comment]
@unterkontrolle Yes, I think it would be a nice addition to the library. I would prefer first option. Feel free to submit a PR, it is welcome.

**Comment by unterkontrolle** [comment]
I'll have it ready by the end of this week.
