### ISSUE TITLE
Add Example: How to manage a local order book

### ISSUE THREAD

**Issue by wisespace-io** [wisespace-io/binance-rs#6]
See "How to manage a local order book correctly" in the link below to implement the example.

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by gabriel-milan** [comment]
Hi, first of all thank you for your amazing work! Were you able to put it to work with tectonicdb?

**Comment by wisespace-io** [comment]
@gabriel-milan Thank you. Actually no. I think it can be done caching in memory,

See how the python library implements: https://github.com/sammchardy/python-binance/blob/master/binance/depthcache.py

**Comment by gabriel-milan** [comment]
Yeah, I've worked with this Python library on [this project](https://github.com/gabriel-milan/btrader) before, and then decided to rewrite it in Rust for learning purposes. I've managed to put it to work with Rust, but I'm really not sure this is the best way.

**Comment by wisespace-io** [comment]
@gabriel-milan Ok, I see. In this case, we may try https://docs.rs/crate/tectonicdb/0.5.2 ... it is a database to manage order book  ticks, so it may be more suitable for your project. It does not seen to be hard to use, based on documentation.

**Comment by gabriel-milan** [comment]
That's probably correct, I'll take a look at it. Thank you very much!
