### ISSUE TITLE
Stop orders

### ISSUE THREAD

**Issue by MichalLebeda** [wisespace-io/binance-rs#62]
Hi, would like to use stop orders but I'm a bit confused, does this crate implement stop orders? It seems like it doesn't but not sure. Official API documentation contains:  
* LIMIT
* MARKET
* STOP_LOSS
* STOP_LOSS_LIMIT
* TAKE_PROFIT
* TAKE_PROFIT_LIMIT
* LIMIT_MAKER

**Comment by wisespace-io** [comment]
@MichalLebeda It is not implemented. It is an important feature but I did not have time to test and implement it.

**Comment by MichalLebeda** [comment]
Initially I though about implementing it myself but I don't trade on binance anymore. Maybe I will in the future
