### ISSUE TITLE
Stop limits on buy and sell

### ISSUE THREAD

**Issue by motters** [wisespace-io/binance-rs#64]
Super cool crate, works perfectly. 

However is is possible when summitting a buy or sell order to use a [stop-limit](https://www.binance.com/en/support/articles/360033779452-Types-of-Order)? 

I've take a quick look and can't see the feature in your library. Looking at [Binance's api ](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade) it does show it's possible.

If this features does not exist would it be best to expand on custom_order or create a new stop_loss_custom_order?

**Comment by wisespace-io** [comment]
@motters  Glad that the crate is useful to you. Regarding your question, Stop Loss is nor supported in the crate yet. 

You could try to extend custom_order, but I would just create a new method, stop_loss_order.

**Comment by motters** [comment]
@wisespace-io Alright sweet, I'll sort a pull request out once it's done.

**Comment by ppamorim** [comment]
@motters Please check the PR #83.

**Comment by ppamorim** [comment]
@wisespace-io Could you please close the issue?
