### ISSUE TITLE
Add Binance.US support

### ISSUE THREAD

**Issue by gmale** [wisespace-io/binance-rs#74]
Can this library be modified to make it easier to use with Binance.US? In most cases, this involves using endpoints like `api.binance.us` instead of `api.binance.com`. As far as I'm aware, the APIs are identical.

In most places, static constants seem to be used for defining hosts, particularly when it comes to websockets. It might be nice to create an Enum of supported hosts and then allow that to be passed into the `Binance::new` and `WebSockets::connect` functions.

**Comment by dorak88783** [comment]
This can be added to the scope of issue https://github.com/wisespace-io/binance-rs/issues/61; there's a proposal there how to implement this.

**Comment by wisespace-io** [comment]
@gmale We just released a new version which supports this. Please check https://github.com/wisespace-io/binance-rs#testnet-and-api-clusters
Kudos to @dorak88783
