### ISSUE TITLE
Auto(?) merge for pull-request #83 breaks everything

### ISSUE THREAD

**Issue by MrNbaYoh** [wisespace-io/binance-rs#87]
The auto (?) merge for pull request #83  on commit f8f7efdd530f3a319a71058740eb3ed16d740f14 introduces duplicate declarations & other merging-related issues leading to compilation errors.

**Comment by wisespace-io** [comment]
@MrNbaYoh I think it will be fixed when we merge https://github.com/wisespace-io/binance-rs/pull/84, @ppamorim right?

**Comment by ppamorim** [comment]
@wisespace-io This was caused because #85 was merged before #84. I opened a PR reverting these changes.
